"""add notified_24h_at

Revision ID: 5a7ec2ea3428
Revises: fbe3760f8ab8
Create Date: 2026-01-23 22:40:51.077487

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5a7ec2ea3428'
down_revision = 'fbe3760f8ab8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('activity_registration', schema=None) as batch_op:
        batch_op.add_column(sa.Column('notified_24h_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('activity_registration', schema=None) as batch_op:
        batch_op.drop_column('notified_24h_at')

    # ### end Alembic commands ###
